// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";

// Load environment variables from both .env and .env.local
// Priority: .env.local (Next.js convention) > .env (Prisma convention)
config({ path: ".env" }); // Load .env first (lower priority)
config({ path: ".env.local", override: true }); // Override with .env.local (higher priority)

import { defineConfig, env } from "prisma/config";

/**
 * Prisma Configuration for CLI Operations
 * 
 * IMPORTANT: This configuration is ONLY used by Prisma CLI tools:
 * - prisma migrate (migrations)
 * - prisma studio (database browser)
 * - prisma db (database commands)
 * - prisma generate (client generation)
 * 
 * Prisma CLI requires DATABASE_URL_DIRECT (direct postgresql:// connection).
 * Prisma Studio does NOT support prisma+postgres:// protocol.
 * 
 * Runtime database connections (Next.js app) use DATABASE_URL instead,
 * which may be prisma+postgres:// (Accelerate/Data Proxy) or direct postgresql://.
 * See src/lib/prisma.ts for runtime connection handling.
 */
const isProduction = process.env.VERCEL_ENV === "production" || process.env.NODE_ENV === "production";

// Prisma CLI operations require DATABASE_URL_DIRECT (direct postgresql:// connection)
// For non-production build-time client generation, allow fallback
// (prisma generate doesn't need a real DB connection, only migrations do)
// In Vercel/production, fall back to DATABASE_URL if DATABASE_URL_DIRECT is not set
// Note: If DATABASE_URL uses prisma+postgres://, migrations may fail (Prisma Studio won't work)
const databaseUrl =
  process.env.DATABASE_URL_DIRECT ||
  process.env.DATABASE_URL ||
  "postgresql://placeholder:placeholder@localhost:5432/placeholder";

// In production, it's strongly recommended to provide DATABASE_URL_DIRECT for CLI operations.
// We do NOT hard-fail here because some deployments/builds intentionally run in "no-db" mode.
if (isProduction && !process.env.DATABASE_URL_DIRECT && !process.env.DATABASE_URL) {
  console.warn(
    "[Prisma Config] WARNING: DATABASE_URL_DIRECT and DATABASE_URL are missing. Prisma migrations will be skipped/fail; builds may run in no-db mode."
  );
}

// Warn if using prisma+postgres:// in production (migrations may fail)
if (isProduction && databaseUrl.startsWith("prisma+postgres://")) {
  console.warn("[Prisma Config] WARNING: Using prisma+postgres:// for migrations. Set DATABASE_URL_DIRECT with direct postgresql:// for best compatibility.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Note: Shadow database is handled via environment variable SHADOW_DATABASE_URL
    // If not set, Prisma will attempt to create a temporary shadow database
    // For mature migration histories, you may need to provide a separate shadow database
  },
  datasource: {
    url: databaseUrl,
    // Optional shadow DB for migrate dev only. Not used in this repo's default workflow.
    // We use `prisma migrate deploy` instead, which doesn't require a shadow database.
    ...(process.env.SHADOW_DATABASE_URL && { shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL }),
  },
});
