// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";

// Load environment variables from both .env and .env.local
// Priority: .env.local (Next.js convention) > .env (Prisma convention)
config({ path: ".env" }); // Load .env first (lower priority)
config({ path: ".env.local", override: true }); // Override with .env.local (higher priority)

import { defineConfig, env } from "prisma/config";

/**
 * Prisma Configuration for CLI Operations
 * 
 * IMPORTANT: This configuration is ONLY used by Prisma CLI tools:
 * - prisma migrate (migrations)
 * - prisma studio (database browser)
 * - prisma db (database commands)
 * - prisma generate (client generation)
 * 
 * Prisma CLI requires DATABASE_URL_DIRECT (direct postgresql:// connection).
 * Prisma Studio does NOT support prisma+postgres:// protocol.
 * 
 * Runtime database connections (Next.js app) use DATABASE_URL instead,
 * which may be prisma+postgres:// (Accelerate/Data Proxy) or direct postgresql://.
 * See src/lib/prisma.ts for runtime connection handling.
 */
const isProduction = process.env.VERCEL_ENV === "production" || process.env.NODE_ENV === "production";

// Prisma CLI operations require DATABASE_URL_DIRECT (direct postgresql:// connection)
// For non-production build-time client generation, allow fallback
// (prisma generate doesn't need a real DB connection, only migrations do)
const databaseUrl = process.env.DATABASE_URL_DIRECT || 
  (isProduction 
    ? (() => { throw new Error("DATABASE_URL_DIRECT is required in production for Prisma CLI operations"); })()
    : "postgresql://placeholder:placeholder@localhost:5432/placeholder"
  );

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
