"use client";

import { useMemo, useState } from "react";
import { runBDWHealthCheck, type HealthCheckReport, type HealthCheckItem } from "@/lib/utils/bdw-health-check";

interface BusinessDescriptionFormValues {
  businessName: string;
  businessType: string;
  services: string;
  city: string;
  state: string;
  targetAudience: string;
  uniqueSellingPoints: string;
  keywords: string;
  brandVoice: string;
  personalityStyle?: string | "";
  writingStyleTemplate: string;
  includeFAQSuggestions: boolean;
  includeMetaDescription: boolean;
  descriptionLength: string;
  language: string;
}

interface BusinessDescriptionResponse {
  obdListingDescription: string;
  websiteAboutUs: string;
  googleBusinessDescription: string;
  socialBioPack: {
    facebookBio: string;
    instagramBio: string;
    xBio: string;
    linkedinTagline: string;
  };
  taglineOptions: string[];
  elevatorPitch: string;
  faqSuggestions: Array<{
    question: string;
    answer: string;
  }>;
  metaDescription: string | null;
}

interface DescriptionHealthCheckProps {
  formValues: BusinessDescriptionFormValues;
  result: BusinessDescriptionResponse | null;
  isDark: boolean;
  isV4Enabled: boolean;
}

function getSeverityColor(severity: HealthCheckItem["severity"], isDark: boolean): string {
  switch (severity) {
    case "ok":
      return isDark ? "text-green-400" : "text-green-600";
    case "warn":
      return isDark ? "text-yellow-400" : "text-yellow-600";
    case "info":
      return isDark ? "text-blue-400" : "text-blue-600";
    default:
      return isDark ? "text-slate-400" : "text-slate-600";
  }
}

function getSeverityIcon(severity: HealthCheckItem["severity"]): string {
  switch (severity) {
    case "ok":
      return "✓";
    case "warn":
      return "⚠";
    case "info":
      return "ℹ";
    default:
      return "•";
  }
}

function getScoreColor(score: number, isDark: boolean): string {
  if (score >= 90) {
    return isDark ? "text-green-400" : "text-green-600";
  } else if (score >= 70) {
    return isDark ? "text-yellow-400" : "text-yellow-600";
  } else {
    return isDark ? "text-red-400" : "text-red-600";
  }
}

function formatReportAsText(report: HealthCheckReport): string {
  const lines: string[] = [];
  lines.push("BDW Description Health Check Report");
  lines.push("=".repeat(40));
  lines.push(`Score: ${report.score}/100`);
  lines.push("");
  
  if (report.items.length === 0) {
    lines.push("No issues found. Your descriptions look great!");
  } else {
    lines.push(`Found ${report.items.length} suggestion${report.items.length > 1 ? "s" : ""}:`);
    lines.push("");
    
    report.items.forEach((item, idx) => {
      lines.push(`${idx + 1}. [${item.severity.toUpperCase()}] ${item.title}`);
      lines.push(`   ${item.detail}`);
      if (item.fixHint) {
        lines.push(`   💡 ${item.fixHint}`);
      }
      lines.push("");
    });
  }
  
  lines.push("=".repeat(40));
  lines.push("Generated by OBD AI Business Description Writer");
  
  return lines.join("\n");
}

export default function DescriptionHealthCheck({
  formValues,
  result,
  isDark,
  isV4Enabled,
}: DescriptionHealthCheckProps) {
  const [reportCopied, setReportCopied] = useState(false);

  const report: HealthCheckReport | null = useMemo(() => {
    if (!result || !isV4Enabled) {
      return null;
    }

    try {
      return runBDWHealthCheck({
        inputs: {
          businessName: formValues.businessName || "",
          city: formValues.city || undefined,
          state: formValues.state || undefined,
          services: formValues.services || undefined,
          businessType: formValues.businessType || undefined,
        },
        outputs: {
          obdListingDescription: result.obdListingDescription || null,
          googleBusinessDescription: result.googleBusinessDescription || null,
          websiteAboutUs: result.websiteAboutUs || null,
          elevatorPitch: result.elevatorPitch || null,
          metaDescription: result.metaDescription || null,
        },
      });
    } catch (error) {
      console.error("[BDW Health Check] Error running health check:", error);
      return null;
    }
  }, [result, formValues, isV4Enabled]);

  if (!isV4Enabled || !result || !report) {
    return null;
  }

  const handleCopyReport = async () => {
    if (!report) return;

    try {
      const reportText = formatReportAsText(report);
      await navigator.clipboard.writeText(reportText);
      setReportCopied(true);
      setTimeout(() => setReportCopied(false), 2000);
    } catch (error) {
      console.error("Failed to copy report:", error);
      alert("Failed to copy report. Please try again.");
    }
  };

  return (
    <div className={`rounded-xl border p-4 ${
      isDark
        ? "bg-slate-800/50 border-slate-700"
        : "bg-slate-50 border-slate-200"
    }`}>
      <div className="flex items-start justify-between mb-3">
        <div>
          <h3 className={`text-sm font-semibold mb-1 ${
            isDark ? "text-white" : "text-slate-900"
          }`}>
            Description Health Check
          </h3>
          <p className={`text-xs ${
            isDark ? "text-slate-400" : "text-slate-500"
          }`}>
            Suggestions to improve clarity and local SEO (no changes made automatically).
          </p>
        </div>
        <div className={`text-2xl font-bold ${getScoreColor(report.score, isDark)}`}>
          {report.score}
        </div>
      </div>

      {report.items.length === 0 ? (
        <div className={`text-sm mt-3 ${
          isDark ? "text-slate-300" : "text-slate-700"
        }`}>
          ✓ No issues found. Your descriptions look great!
        </div>
      ) : (
        <>
          <div className="space-y-2 mt-4">
            {report.items.map((item) => (
              <div
                key={item.id}
                className={`rounded-lg border p-3 ${
                  isDark
                    ? "bg-slate-900/50 border-slate-600"
                    : "bg-white border-slate-300"
                }`}
              >
                <div className="flex items-start gap-2">
                  <span className={`text-sm font-medium ${getSeverityColor(item.severity, isDark)}`}>
                    {getSeverityIcon(item.severity)}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className={`text-sm font-medium mb-1 ${
                      isDark ? "text-slate-200" : "text-slate-800"
                    }`}>
                      {item.title}
                    </div>
                    <div className={`text-xs ${
                      isDark ? "text-slate-400" : "text-slate-600"
                    }`}>
                      {item.detail}
                    </div>
                    {item.fixHint && (
                      <div className={`text-xs mt-1 ${
                        isDark ? "text-blue-400" : "text-blue-600"
                      }`}>
                        💡 {item.fixHint}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-4 pt-3 border-t border-slate-300 dark:border-slate-600">
            <button
              onClick={handleCopyReport}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                isDark
                  ? "bg-slate-700 text-slate-200 hover:bg-slate-600"
                  : "bg-white text-slate-700 hover:bg-slate-100 border border-slate-200"
              }`}
            >
              {reportCopied ? "Copied!" : "Copy Report"}
            </button>
          </div>
        </>
      )}
    </div>
  );
}

